apiVersion: apps/v1
kind: Deployment
metadata:
  name: tennis-tournament
spec:
  selector:
    matchLabels:
      app: tennis-tournament
  replicas: 3
  template:
    metadata:
      labels:
        app: tennis-tournament
    spec:
      containers:
        - name: tennis-tournament
          image: tournamentacr.azurecr.io/rortizpe/tennis-tournament:#{Build.BuildId}#
          imagePullPolicy: Always
          ports:
            - containerPort: 8110
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tennis-tournament
    k8s-app: tennis-tournament
  name: tennis-tournament
spec:
  selector:
    app: tennis-tournament
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8110
  type: LoadBalancer